// <auto-generated />
using System;
using LocalizaApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalizaApi.Migrations
{
    [DbContext(typeof(BancoDadosContext))]
    [Migration("20220727143908_Clientes")]
    partial class Clientes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LocalizaApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cliente"), 1L, 1);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Nivel_Acesso")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id_Cliente");

                    b.ToTable("tab_Cliente");
                });

            modelBuilder.Entity("LocalizaApi.Models.Veiculo_Modelo", b =>
                {
                    b.Property<int>("Id_Marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Marca"), 1L, 1);

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id_Marca");

                    b.ToTable("tb_Veiculo_Modelo");
                });

            modelBuilder.Entity("LocalizaApi.Models.Veiculos", b =>
                {
                    b.Property<int>("Id_Veiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Veiculo"), 1L, 1);

                    b.Property<string>("Ano")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Codigo_Marca")
                        .HasColumnType("int");

                    b.Property<string>("Combustivel")
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Limite_PortaMala")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(15,2)");

                    b.HasKey("Id_Veiculo");

                    b.HasIndex("Codigo_Marca");

                    b.ToTable("tab_Veiculo");
                });

            modelBuilder.Entity("LocalizaApi.Models.Veiculos", b =>
                {
                    b.HasOne("LocalizaApi.Models.Veiculo_Modelo", "Marca")
                        .WithMany()
                        .HasForeignKey("Codigo_Marca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });
#pragma warning restore 612, 618
        }
    }
}
