// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Localiza.Data.Models
{
    public partial class localizaDBContext : DbContext
    {
        public localizaDBContext()
        {
        }

        public localizaDBContext(DbContextOptions<localizaDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TabCliente> TabCliente { get; set; }
        public virtual DbSet<TabLocacao> TabLocacao { get; set; }
        public virtual DbSet<TabVeiculo> TabVeiculo { get; set; }
        public virtual DbSet<TbVeiculoModelo> TbVeiculoModelo { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-FERRARI;Initial Catalog=localizaDB;User ID=sa;Password=1");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TabLocacao>(entity =>
            {
                entity.HasKey(e => e.IdAgendamento)
                    .HasName("PK_Tab_Locacão");

                entity.HasOne(d => d.CodigoVeiculoNavigation)
                    .WithMany(p => p.TabLocacao)
                    .HasForeignKey(d => d.CodigoVeiculo)
                    .HasConstraintName("FK_Tab_Locacao_Veiculo");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}