// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Localiza.Data.Models
{
    public partial class localizaDBContext : DbContext
    {
        public localizaDBContext()
        {
        }

        public localizaDBContext(DbContextOptions<localizaDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TabCliente> TabCliente { get; set; }
        public virtual DbSet<TabVeiculo> TabVeiculo { get; set; }
        public virtual DbSet<TbVeiculoModelo> TbVeiculoModelo { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-FERRARI;Initial Catalog=localizaDB;User ID=sa;Password=1");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}