// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Localiza.Data.Models
{
    [Table("Tab_Locacao")]
    public partial class TabLocacao
    {
        [Key]
        [Column("id_Agendamento")]
        public int IdAgendamento { get; set; }
        [Column("Codigo_Veiculo")]
        public int? CodigoVeiculo { get; set; }
        [Column("Data_Inicial", TypeName = "datetime")]
        public DateTime? DataInicial { get; set; }
        [Column("Data_Final", TypeName = "datetime")]
        public DateTime? DataFinal { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Total { get; set; }
        [Column("Carro_Limpo")]
        public bool? CarroLimpo { get; set; }
        [Column("Tanque_Cheio")]
        public bool? TanqueCheio { get; set; }
        public bool? Amassados { get; set; }
        public bool? Arranhoes { get; set; }

        [ForeignKey("CodigoVeiculo")]
        [InverseProperty("TabLocacao")]
        public virtual TabVeiculo CodigoVeiculoNavigation { get; set; }
    }
}