// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Localiza.Data.Models
{
    [Table("tab_Veiculo")]
    [Index("CodigoMarca", Name = "IX_tab_Veiculo_Codigo_Marca")]
    public partial class TabVeiculo
    {
        [Key]
        [Column("Id_Veiculo")]
        public int IdVeiculo { get; set; }
        [StringLength(10)]
        public string Placa { get; set; }
        [Column("Codigo_Marca")]
        public int CodigoMarca { get; set; }
        [StringLength(4)]
        public string Ano { get; set; }
        [Column(TypeName = "numeric(15, 2)")]
        public decimal Valor { get; set; }
        [StringLength(35)]
        public string Combustivel { get; set; }
        [Column("Limite_PortaMala")]
        [StringLength(100)]
        public string LimitePortaMala { get; set; }
        [StringLength(50)]
        public string Categoria { get; set; }

        [ForeignKey("CodigoMarca")]
        [InverseProperty("TabVeiculo")]
        public virtual TbVeiculoModelo CodigoMarcaNavigation { get; set; }
    }
}