// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Localiza.Data.Models
{
    [Table("tb_Veiculo_Modelo")]
    public partial class TbVeiculoModelo
    {
        public TbVeiculoModelo()
        {
            TabVeiculo = new HashSet<TabVeiculo>();
        }

        [Key]
        [Column("Id_Marca")]
        public int IdMarca { get; set; }
        [StringLength(80)]
        public string Marca { get; set; }
        [StringLength(80)]
        public string Modelo { get; set; }

        [InverseProperty("CodigoMarcaNavigation")]
        public virtual ICollection<TabVeiculo> TabVeiculo { get; set; }
    }
}